# Generated by Django 3.2.5 on 2021-07-13 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_short_names(apps, schema_editor):
    Author = apps.get_model('books', 'Author')
    for author in Author.objects.all():
        author.short_name = '%s' % (author.first_name)
        author.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_rename_publication_year_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunPython(populate_short_names),
        migrations.AlterField(
            model_name='author',
            name='short_name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='area_of_interest',
            field=models.CharField(choices=[
                                        ('Classic', 'Classic'),
                                        ('Fiction', 'Fiction'),
                                        ('Comedy', 'Comedy'),
                                        ('Romance', 'Romance'),
                                        ('Horror', 'Horror'),
                                        ('History', 'History')
                                   ], default='Classic', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user',
                                       to=settings.AUTH_USER_MODEL
                                       ),
        ),
    ]
